### PR TITLE
Added build support for Ubuntu Impish and Bionic

### PR DESCRIPTION
**Pull request by gornostal**
Added build support for Ubuntu Impish and Bionic

### CODE REVIEW

**Comment by gornostal** [comment]
I've merged this commit to master too

**Comment by friday** [comment]
> I've merged this commit to master too

I stopped using master, because it sort of had no purpose, and we have a v6 branch for the most active development currently (removed Xenial build target there as well, but didn't add back Bionic or add Impish).

Bionic is already unsupported by Ubuntu, apart from security updates. Is the aim to support the same as the "Security Support" column here? https://endoflife.date/ubuntu

Regarding master, we could remove it, or use it to sync with releases. Initially I did the latter, but it didn't really serve any cause other than to have it updated.

**Comment by gornostal** [comment]
Then we sold probably remove master branch.

Bionic's end of support is April 2023. https://wiki.ubuntu.com/Releases
Or am I missing something?

**Comment by friday** [comment]
Must be endoflife.date that has the info wrong then. Strange that they can get it so wrong. I found that recently when searching for that Ubuntu page, and have been using it since since it's much easier to read.

**Pull request merged**
