### PR TITLE
Feature: Option to enable/disable shortcuts

### PR DESCRIPTION
**Pull request by goodwillcoding**
Rationale: Alt+<num/letter> is not required for everyone, since it's
often faster to type the completion then use Alt key.
I found this to be most problematic on laptops where the Alt key
is small and lifting fingers to get to Alt+<key>.

PR below includes tests for all the new and updated scenarios.
Also the enabling of shortcuts is still the default in keeping with current behaviour.

This PR might also address #133 (can not tell from it's phrasing)

### CODE REVIEW

**Comment by goodwillcoding** [comment]
@goodwillcoding is there anything you need from me on this PR. Or do you think it's too much?

**Comment by gornostal** [comment]
>  is not required for everyone, since it's often faster to type the completion then use Alt key.

I agree with that. I'm not sure what problem this improvement solves exactly. It only removes Alt keys from the UI and disables them, right?

**Comment by goodwillcoding** [comment]
> It only removes Alt keys from the UI and disables them, right?

That's correct, with togglable option. The default is still to show/enable Alt keys

**Comment by goodwillcoding** [comment]
I think? it's what #133 was requesting.

**Comment by gornostal** [comment]
> I think? it's what #133 was requesting.

Ah, that's actually a different thing. The requestin #133 is about disabling shortcuts in the Preferences. We have shortcuts there that people may want to disable so they don't appear among search results.

Sorry about the confusing title.

**Comment by goodwillcoding** [comment]
@gornostal ... all good. any thought on the feature itself?

**Comment by gornostal** [comment]
Sorry, but I don't think this improvement is necessary.
The reason is that I want to keep preferences as simple as possible, and also to have as minimum code as possible in order to make maintenance easier.

Once we migrate to python3 I will merge #300. I think that's a really good improvement

**Comment by goodwillcoding** [comment]
kie, I'll just keep my branch of this code.

**Comment by goodwillcoding** [comment]
@gornostal ... if we want to pair down the preferences code, should we consider moving it into Gtk and out of JS/Vue? That would definately cut down on maintenance.

**Comment by gornostal** [comment]
> should we consider moving it into Gtk and out of JS/Vue?

That was the first thing I've tried and I realized that customizing UI in GTK is pain. Whe I re-implemented Preferences in JS it was much easier to add stuff and to make the UI look pretty.

**Comment by gornostal** [comment]
I'm going to close this PR now

**Pull request closed without merging**
