### PR TITLE
Explicitly import versions for all Gnome related libraries.

### PR DESCRIPTION
**Pull request by troycurtisjr**
### Link to related issue (if applicable)
#703 

### Summary of the changes in this PR
There are some usages of Gnome libraries in various modules which do not specify a specific version. Now that systems are starting to ship with Gtk4 installed, this means that Gtk4 is picked by default. Not only might this version change cause generally surprising behavior, but if an extension then later tries to explicitly call out the Gtk3 libraries there is an exception, since the Gtk4 libraries are already loaded.

Technically it looks like all the is needed to address #703 is to do the explicit import in the `utils/display.py`, at least with the extensions I tested with. However, the same situation can happen if an extension inherited ANY of the modules lacking the explicit version call out, so I thought it was useful to just set them all now. I specifically did not set them in the test files, since those are really internal use only to Ulauncher and it didn't seem necessary.

### Checklist (see more [here](https://github.com/Ulauncher/Ulauncher/wiki/Code-Contribution))
- [x] Use `dev` as the base branch
- [x] Follow the [Python Code Style Guides](https://github.com/Ulauncher/Ulauncher/wiki/Python-Code-Style-Guides)
- [x] Write unit tests for your changes when applicable
- [x] If your changes alters the behavior or introduce new functionality, please update the documentation accordingly
- [x] All tests are passing

### Tested environment (distro, desktop environment and their versions)
Fedora 34 Beta, Gnome 40 rc1

### CODE REVIEW

**Comment by troycurtisjr** [comment]
Any chance this can be considered for merge?

**Comment by LJ-Court** [comment]
Please merge this as soon as possible to allow extensions to continue working

**Comment by friday** [comment]
@gornostal This PR is pretty straight forward to merge imo, and fixes a critical issue breaking all extensions (unless *they* specify `gi.require_version('Gdk', '3.0')`) if the user has GDK4 (required by Gnome 40).

**Comment by mpldr** [comment]
When is the next expected merge-day? Not being able to use extensions is a bit of a big deal and since GTK4 is default on Arch now this also affects a lot of users. 2 months is a lot of time for such a small PR.

**Comment by BadassHenkka** [comment]
Fedora 34 has officially been out for a couple of months now and a lot of extensions are crashing because of this. Would be awesome if this could be merged.

**Comment by friday** [comment]
Thanks for submitting this PR @troycurtisjr. I merged it into my fork https://github.com/friday/Ulauncher-Revived. I'm planning on keeping this project alive since @gornostal went AWOL and is not responding, while a growing part of the user base are unable to use extensions. Hopefully he comes back to support the project or at least tell us more on the status.

**Pull request merged**
