### PR TITLE
remove ul, update, cleanup & fix Nix code

### LINKED ISSUE #1340: v6: doesn't start on Nix/NixOS
### Environment

NixOS

### Bug description

I just tried updating (noticed I had old version pinned) Ulauncher and got the error described below

This is mostly a note to myself to not forget to fix it when I have some time to spare.

https://github.com/nazarewk-iac/nix-configs/commit/fa799252ba69c3e840be1c26f3c9035d95e36c58

### Log output

```shell
kdn@krul ~/d/g/n/nix-configs (main) [1]> ucs ulauncher.service
● ulauncher.service - Ulauncher service
     Loaded: loaded (/home/kdn/.config/systemd/user/ulauncher.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2024-02-09 14:21:25 CET; 2s ago
       Docs: https://ulauncher.io/
    Process: 512852 ExecStart=/nix/store/xj01bb7npc4xfqv08d49fx78yijvqvs3-python3.11-ulauncher-v6/bin/ulauncher --no-window (code=exited, status=1/FAILURE)
   Main PID: 512852 (code=exited, status=1/FAILURE)
        CPU: 172ms
kdn@krul ~/d/g/n/nix-configs (main) [3]> /nix/store/xj01bb7npc4xfqv08d49fx78yijvqvs3-python3.11-ulauncher-v6/bin/ulauncher
Ulauncher is not properly installed on your system.
Please install or reinstall Ulauncher, and ensure you are not overriding your system Python version
kdn@krul ~/d/g/n/nix-configs (main) [1]>
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

### PR DESCRIPTION
**Pull request by nazarewk**
fixes #1340

### CODE REVIEW

**Review by friday — APPROVED** [review]
LGTM. The last commit can be amended now in favor of https://github.com/Ulauncher/Ulauncher/commit/c545ec0cf7effd234e159406f62c0289e065b94c

The debug commit seems like a good idea to keep I think?

**Comment by nazarewk** [comment]
I think I'll still use an opportunity to make a test fail with useful message on this error

**Comment by nazarewk** [comment]
I'm not sure why it hangs up in the CI, fails or exits immediately on my computer

**Comment by friday** [comment]
> I'm not sure why it hangs up in the CI, fails or exits immediately on my computer

I cancelled one of the runs.

Perhaps you can set a timeout to 5 or something while you're testing this? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes

**Comment by friday** [comment]
Looks like it complained about the icons? I never liked installing them the way we do now, so I'm more than open to changing this.

**Comment by nazarewk** [comment]
> Looks like it complained about the icons? I never liked installing them the way we do now, so I'm more than open to changing this.
> 
> I don't know how it picked up "ulauncher-indicator-ltr", but I'm sure it happens because of this: [`v6`/setup.py#L40](https://github.com/Ulauncher/Ulauncher/blob/v6/setup.py?rgh-link-date=2024-02-12T18%3A32%3A08Z#L40) Basically we install the icons so users/icon theme creators can override them, but we should probably try to load "ulauncher-indicator" from the theme and fallback to the fixed path to the data dir.

I don't think this is issue we want to tackle here at all.

**Comment by friday** [comment]
> I don't think this is issue we want to tackle here at all, this one works fine on a running system.

Yes. But there's at least a couple more issues with this solution, so I can look at it separately from this PR (not until this weekend though).

**Comment by nazarewk** [comment]
seems like the process control works differently in the CI than locally... maybe because of Nix's single-user mode in the CI

**Comment by nazarewk** [comment]
I'm at complete loss, this seems to be Github overriding commit runs with something in it's own reality:
- this repo having unexpected/impossible (successful) outcome https://github.com/Ulauncher/Ulauncher/actions/runs/7877114118/job/21492584100?pr=1344
- my repo run having expected (failing) outcome https://github.com/nazarewk/Ulauncher/actions/runs/7877113893

image

**Comment by nazarewk** [comment]
Yeah, pull request run seems to be checking out the wrong commit:

incorrect:
https://github.com/Ulauncher/Ulauncher/actions/runs/7877114118/job/21492584100?pr=1344#step:3:42
image


correct:
https://github.com/nazarewk/Ulauncher/actions/runs/7877113893/job/21492583439#step:3:42
image

**Comment by friday** [comment]
Very strange

**Comment by nazarewk** [comment]
this is way too much magic for my brain...

`push` trigger is running on my own commit https://github.com/Ulauncher/Ulauncher/pull/1344/commits/1ad6bd8488b0f2b09f5fbf762f809ccdded2fdab

what actually happens is that `pull request` trigger is running against not-yet-existing/pushed `merge` commit https://github.com/Ulauncher/Ulauncher/commit/987c90513856666257b96cf37daff394fdf4462c

**Comment by nazarewk** [comment]
So I guess the `pull request` status is telling you what happens after you merge this PR into current `master`

**Comment by nazarewk** [comment]
so after all we can merge the PR without rebasing onto/merging master into my branch because the CI has already run successfully for this exact case.

**Comment by friday** [comment]
> So I guess the `pull request` status is telling you what happens after you merge this PR into current `master`, but doesn't tell you it's doing so.
> 
> It also seems to be retroactively updating the failing runs with the new post-merge links, when I was writing the previous post the commit status linked to https://github.com/nazarewk/Ulauncher/actions/runs/7877273633/job/21493098526#step:11:2581 , but now it links to https://github.com/Ulauncher/Ulauncher/actions/runs/7877273885/job/21493099743?pr=1344#step:11:2596

Yeah, that's true. I should have figured it out but I was working late yesterday so this PR didn't have my attention. 

The thought with the `pull_request` trigger is that upstream changes like renaming a method of a library that the PR uses can still break the PR once merged, even if it works before and there are no conflicts, so normally it's the one you want to verify.

It used to check both for every commit. You can set `on` to `[push, pull_request]` to restore that or just `[push]` if you want to only test the pushes.

**Review by friday — APPROVED** [review]
Looks great. Ready to merge this if you are done?

**Pull request merged**
