### PR TITLE
Fix html entities

### PR DESCRIPTION
**Pull request by Laurens256**
Very simple fix for unescaping html entities in the search results. Something like this might also be useful for fuzzy searching (and possibly extended to make `and` match `&`). For now though, this simply fixes https://github.com/Ulauncher/Ulauncher/issues/1288

### CODE REVIEW

**Comment by Laurens256** [comment]
whoops

**Comment by Laurens256** [comment]
Somehow I added all the commits from the [search highlighting change](https://github.com/Ulauncher/Ulauncher/pull/1293) in this as well lmao. It's a very minor change though, you can just add these lines in some other push if you think the changes are okay

**Comment by friday** [comment]
I didn't have this issue myself. I had the opposite issue where set_markup wouldn't work because they were already unescaped. But it seems safe and good if you got the &amp; showing in the result?

I think it's better that we merge #1293 first though since we're making changes in some of the same places, and we can cherry pick this after.

**Comment by friday** [comment]
cherry-picked as e62850e0a3142cb3b51d7761c1d0371fc97da6bc

**Pull request closed without merging**
