### PR TITLE
Add event.get_keyword_id()

### PR DESCRIPTION
**Pull request by friday**
Implements #284 

Criticism is welcome. I'm not a python dev and don't know the Ulauncher internals or your conventions well

Update: Know the tests are broken. Will have a look at this soon

### CODE REVIEW

**Comment by gornostal** [comment]
Thanks for the PR @friday 
Implementation of `get_keyword_id` looks good to me. However, I need to bump API version and run some checks on different extensions before merging it.

**Comment by friday** [comment]
I'm not in a hurry, since this can be done in the client code as well. Don't think this should be API-breaking but you would know better. Perhaps it makes sense to coordinate this with other features. 

As mentioned I'm aware I broke the tests (and also haven't added any for `get_keyword_id()`). Will look at the broken test(s) soon.

**Comment by friday** [comment]
Fixed the tests, but you may want to do it differently.

**Comment by friday** [comment]
Should work now. It actually did before too, with just a lint error. I fixed it with 4b5900b. Personally I think this commit is dumb and more likely to obfuscate errors than fix them. Feel free to revert or skip it.

I updated https://github.com/friday/ulauncher-gnome-settings to use the new API, so you can test it, at least of you have Gnome Settings (formerly Gnome Control Center).

**Comment by gornostal** [comment]
Cool. Thank you!

**Comment by gornostal** [comment]
@friday sorry, I had to revert.

I didn't notice at first that you pass `preference` object into event. That causes an error.
Also, an event object is supposed to be lightweight. I would not pass anything like that.

It's better to have the function that returns keyword ID in the extension. You have the entire extension object with preferences in every `on_event` callback.

**Comment by friday** [comment]
Alright. So every extension that needs the id has to do this then?

I didn't notice any errors while linting or building. I'm also unable to get the docker image running (I'm running it on my native environment), but I don't think that should matter.

**Comment by gornostal** [comment]
> I didn't notice any errors while linting or building
I've changed a few things after which it caused an error.

> So every extension that needs the id has to do this then?

I think we could add a helper function `get_keyword_id(preferences, query)` to `ulauncher.api.client.utils`

**Pull request merged**
